apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: 
  CLOUDINARY_KEY: 
  CLOUDINARY_SECRET: 
  MAPBOX_TOKEN: 
  DB_URL: 
  SECRET: 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
      - name: yelp-camp-container
        image: vsingh55/campprod:latest
        ports:
        - containerPort: 3000
        env:
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: yelp-camp-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_KEY
          valueFrom:
            secretKeyRef:
              name: yelp-camp-secrets
              key: CLOUDINARY_KEY
        - name: CLOUDINARY_SECRET
          valueFrom:
            secretKeyRef:
              name: yelp-camp-secrets
              key: CLOUDINARY_SECRET
        - name: MAPBOX_TOKEN
          valueFrom:
            secretKeyRef:
              name: yelp-camp-secrets
              key: MAPBOX_TOKEN
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: yelp-camp-secrets
              key: DB_URL
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: yelp-camp-secrets
              key: SECRET
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: webapps
spec:
  selector:
    app: yelp-camp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
